### ISSUE TITLE
filter namespaces

### ISSUE THREAD

**Issue by mprins** [mprins/dokuwiki-plugin-backlinks#1]
Would be nice if we could add a namespace filter, eg. only display linkbacks from within and below a certain namespace.

**Comment by majnu-campact** [comment]
+1

**Comment by mprins** [comment]
I'm open for a pull request, basically you'd have to modify the syntax a bit to add the namespace to filter and the filter the `$backlinks` array returned by [ft_backlinks](http://xref.dokuwiki.org/reference/dokuwiki/inc/fulltext.php.html#ft_backlinks) somewhere around [line 92](https://github.com/mprins/dokuwiki-plugin-backlinks/blob/master/syntax.php#L92) but after the emtpy check

**Comment by ghost** [comment]
+1
