### ISSUE TITLE
feature request: Allow linking to section which contains backlink

### ISSUE THREAD

**Issue by wrathagom** [mprins/dokuwiki-plugin-backlinks#13]
Just started using backlinks2, so thanks for creating it and maintaining it. when I include the list of backlinks in a page it shows the header of the page and links to that header. I would really like to be able to show the section that contained the backlink and link direct to that backlink.

So say I had a page like this:

```
==== My Page ====

Some content here

=== Second Header ===
[[page2]]
```

Then in the page where I wanted to list backlinks I could do something like this

```
==== Backling to Page 2 ====
{{backlings>.;section=true}}
```

and get output similar to the below

**Backlinks to Page 2**
My Page - Second Header <- which has a link like [[MyPage#SecondHeader]]

Hopefully you can follow all of that. if I get time I may play with it, but PHP is not my forte.

**Comment by mprins** [comment]
Afaik this information is not available in the index or wiki metadata so it would be impossible to do without parsing all pages in a wiki
