### ISSUE TITLE
Plugin name differs from plugin basename what confuses dokuwiki plugin manager

### ISSUE THREAD

**Issue by solewniczak** [mprins/dokuwiki-plugin-backlinks#15]
It's more like opinion rather than an actual bug. I believe that you should rename plugin basedir in plugin.info.txt into "backlinks2". It will be much cleaner than current solution which in addition confuses dokuwiki plugin manager.

**Comment by mprins** [comment]
No, the plugin manager should use the provided URL and not the install directory
