### ISSUE TITLE
~~NOCACHE~~ needed for correct use?

### ISSUE THREAD

**Issue by whnr** [mprins/dokuwiki-plugin-backlinks#17]
## environment

  - php version: PHP 7.0.15-0ubuntu0.16.04.4 (cli) ( NTS )
  - dokuwiki version: Release 2017-02-19b "Frusterick Manners"
  - plugin version / date: 2016-05-28
  - list of any other plugins (apart from bundled plugins): especially on pages where this is used: publish and Autonumbering
  
## expected behaviour

Links updating automatically

## actual behaviour

Link only update with time or ~~NOCACHE~~ enabled.

I think this should be mentioned in the Docs. Or is this just some interference with another plugin?

**Comment by mprins** [comment]
The plugin uses the wiki index, if you have to use nocache your index is out of date.
