### ISSUE TITLE
Plugin uses wrong directory

### ISSUE THREAD

**Issue by igittigitt** [mprins/dokuwiki-plugin-backlinks#18]
As a rule of thumb, plugins directory should follow it's name. This plugin installs as "backlinks" but should install as "backlinks2". It should also conflict to plugin backlinks, because both use same syntax and directory.

**Comment by mprins** [comment]
the confict with the other backlinks plugin is noted in the appropriate field on wiki page, for historic reasons renaming the plugin or installation directory is not an option
