### ISSUE TITLE
numbers of backlink

### ISSUE THREAD

**Issue by 3615pipou** [mprins/dokuwiki-plugin-backlinks#2]
Could it be possible to get the number of links in a page pointing to the current page ? For example, it looks like 
- Ain (1)
- Angillon (1)
- Bienne (4)
- Doubs (3)
- Flumen (1)
- Lison (3)
- Loue (1)
- Saine (5)
- Semine (3)

**Comment by mprins** [comment]
no, this plugin uses DokuWiki's [ft_backlinks](https://github.com/splitbrain/dokuwiki/blob/master/inc/fulltext.php#L145) which does not provide that information. 

Doing this would require full text scans of all wiki pages each time a page is generated instead of doing a lookup in the index

Just out of curiosity: What is you use case for this?

**Comment by 3615pipou** [comment]
Hello, I want to make a documentation on events and persons who participate to these events. So I want to add manually a link only on the wikipage of the events when a person participate to these events. Then the wikipage of the person will be automatically update to say "this person participated to these events". And, in fact I want it to say "this person participated each many times to these events".

Maybe you have an other solution ?

Thanks a lot for considering my request !

**Comment by 3615pipou** [comment]
Someone else seems to need the same thing : https://forum.dokuwiki.org/thread/11895

**Comment by mprins** [comment]
You may be able to do this using the [pagequery](https://www.dokuwiki.org/plugin:pagequery) plugin; it supports regular expressions for search input, though I'm not sure it will generate duplicate links which seems what you are looking to do.

The case you mention on the wiki has similarities but is different; I had a brief discussion with the author at the time.
