### ISSUE TITLE
Compatibility to PHP7

### ISSUE THREAD

**Issue by Juergen-aus-Zuendorf** [mprins/dokuwiki-plugin-backlinks#21]
For compatibility to PHP7 the code has to be changed:

Line 58:
`    function handle($match, $state, $pos, Doku_Handler $handler){`

Line 75:
`    function render($mode, Doku_Renderer $renderer, $data) {`

Best regards
Juergen

**Comment by mprins** [comment]
you must be using an out-of-date version as those things were fixed more than a year ago, see #5
