### ISSUE TITLE
Source seems to be wrong in extension manager

### ISSUE THREAD

**Issue by Juergen-aus-Zuendorf** [mprins/dokuwiki-plugin-backlinks#25]
Hi,

in the extension manager the installation of the plugin seems to be wrong or outdated with the following warning:
![2018-12-07 13_09_06-erweiterungen verwalten schutte-wiki](https://user-images.githubusercontent.com/1800472/49647091-9c6c2d00-fa21-11e8-8ea6-4b8e7d86f4e3.png)

Best regards
Juergen

**Comment by mprins** [comment]
I cannot help your wiki config. As you can see: https://www.dokuwiki.org/plugin:backlinks2 says https://github.com/mprins/dokuwiki-plugin-backlinks/archive/master.zip

**Comment by mprins** [comment]
@Juergen-aus-Koeln I've sent a message to the mailing list as this seems to be a problem in the DW core.

I'm now also faced with this:
![image](https://user-images.githubusercontent.com/1165786/50536890-b6e58200-0b59-11e9-9315-e6d69d8b7bb8.png)

**Comment by mprins** [comment]
I have moved the old, unmaintaned and unsupported backlinks plugin  that was providing the wrong url to backlinks-old in the DW wiki and have moved this plugin to the backlinks page. this should be sorted now or after installing the release of today

**Comment by Juergen-aus-Zuendorf** [comment]
Thank you, now it works!

Best regards
Juergen
