### ISSUE TITLE
Backlinks doesn't support Interwiki links within the site?

### ISSUE THREAD

**Issue by deuts** [mprins/dokuwiki-plugin-backlinks#26]
I have a page that's linked to via an Interwiki Link within the same site. That page is not reflected as a backlink.

Doesn't this plugin support Interwiki links?

**Comment by mprins** [comment]
no, we use the `[ft_backlinks()](https://xref.dokuwiki.org/reference/dokuwiki/nav.html?_functions/ft_backlinks.html)` function from the core that uses the index where  only internal links are available
