### ISSUE TITLE
QUESTION: how do I apply 2 flags please?

### ISSUE THREAD

**Issue by Whyglobaleyes** [mprins/dokuwiki-plugin-backlinks#36]
Thanks for the plugin: I basically depend on it! 

I'd like to be able to apply two / more flags (eg) something like ... {{backlinks>.#!contents #!index }}
I've tried a space, a comman and a semicolon as separators & I tried each separator with and without the second hash-sign. then I figured that my guessing was going to discover the syntax.

Can I do it please?
thanks in advance

BTW Apologies - I don't know how/ where to find the mailing list.

**Comment by mprins** [comment]
It's not supported
