### ISSUE TITLE
After updating Dokuwiki from Hogfather to Igor, no backlings are shown

### ISSUE THREAD

**Issue by scheff** [mprins/dokuwiki-plugin-backlinks#37]
## Description

After updating Dokuwiki from Hogfather to Igor the backlink plugin stopped working.

## environment

  - php version: 7.4
  - dokuwiki version: Release 2022-07-31a "Igor"
  - plugin version / date: 2020-09-27
  - Template: Bootstrap3 v2022-07-27
  - list of any other plugins (apart from bundled plugins):  acl, authad, authldap, authpdo, auth.php, authplain, avatar, backlinks, blockquote, blog, bookcreator, catlist, config, confmanager, dw2pdf edittable, extension, folded, gallery, hidden, iframe, include, info, logviewer, meta, move, odt, pagelist, popularity, revert, safefnrecode, searchindex, searchtablejs, smtp, sortablejs, stale, styling, tablefilterjs, tag, upgrade, usermanager, wrap
  
## expected behaviour

Used in the main area of a page, i.e not in the sidebar or the footer, all backlinks should be displayed

## actual behaviour

The plugin displays »Nothing found‹

**Comment by mprins** [comment]
Current version of the plugin is https://github.com/mprins/dokuwiki-plugin-backlinks/blob/5456002411edc4a86c6ad821ec4ed447b506ab5d/plugin.info.txt#L4

It's clear you have not followed dokuwiki upgrade instructions

**Comment by scheff** [comment]
Hi Mark,

there was no update offered for backlinks before or after upgrading to ›Igor‹. I had to uninstall backlinks and install it again to get the correct version (2022-07-07). But backlinks is still not working, so it is obvious that I missed something else. Could you give me a hint, is there something specific I have to take care about?

TIA

Thomas

**Comment by mprins** [comment]
>  is there something specific I have to take care about

You search index needs to be up to date as noted in the FAQ: https://www.dokuwiki.org/plugin:backlinks#faq

**Comment by scheff** [comment]
Clearing and rebuilding the index did not solve the issue. 

Lastly I restored a backup made before the upgrade and upgraded again. This time your plugin worked well within ›Igor‹. Therefore the issue was  definitely caused by something weird in the upgrade process. 

Thank you for your help.
