### ISSUE TITLE
No output of plugin sometimes

### ISSUE THREAD

**Issue by cmuerau** [mprins/dokuwiki-plugin-backlinks#4]
**Summary:**
In my new Dokuwiki instance the backlinks plugin is unable to perform its job sometimes. 

**Details:**
Backlinks are not shown on the page(s) where the code is included like this:

<code>
{{backlinks>.}}
</code>

When an affected page is called a error message is shown: no backlinks found by plugin (current DW language setting is DE). But the actual backlinks can be shown using the built-in DW core functionality and work as expected.

**Steps take to reproduce issue:**
Due to the random nature of the error I cannot offer steps to reproduce the issue. Just opening the page and sometimes the error message is shown and sometimes not.

Might this be related to same cache or indexes not being up to date?

**Comment by mprins** [comment]
> Might this be related to same cache or indexes not being up to date?

yes it could well be. (You could install the indexer plugin to updateor rebuild the full index)

the plugin just uses the [built-in dokuwiki method](https://github.com/splitbrain/dokuwiki/blob/61a4313f55c7e83e0b78c9c6a8eb2efb13ff0512/inc/fulltext.php#L152) (inc/fulltext.php#ft_backlinks()) to retrieve the list of relations.

**Comment by mprins** [comment]
closing due to user timeout
