### ISSUE TITLE
filtering, include doesn't work ?

### ISSUE THREAD

**Issue by chtiland** [mprins/dokuwiki-plugin-backlinks#6]
Hello !

I try to include backlinks in a page (eg. **aaa:bbb:cc:start**) of pages in one namespace .

A simple, 

`{{backlinks>.}}`

works, but I want only backlinks from one namespace (eg. **ggg:hhh:**)

I tried several syntax like these :  

```
{{backlinks>.#ggg:hhh:}}
{{backlinks>.#ggg:hhh}}
{{backlinks>ggg:hhh:.#ggg:hhh:}}
```

In fact, i tried most of combinations, but nothing work, always "no backlink found"

Do i missed womething ?

**Comment by mprins** [comment]
The abstraction provided in your example baffles me; so I would like for you provide a concrete example/directory tree.

Also: is your wiki index up to date?

**Comment by chtiland** [comment]
In fact I want to show backlink from a namespace (aaa/bbb/ccc/) on another page on another namespace (hhh/iii/jjj/start.txt or any other page).

Index is up to date.

**Comment by mprins** [comment]
If you want to include backlinks to a page from namespace `:aaa:bbb:cc:` in a page the syntax should be `{{backlinks>.#aaa:bbb:cc}}` on that page, as noted in the docs it must be an absolute namespace.

**Comment by moz0817** [comment]
For me include don't work neither. I tried:
- `{{backlinks>.#:linux:}}`
- `{{backlinks>.#linux:}}`
- `{{backlinks>.#:linux}}`

**Comment by chtiland** [comment]
I'd like to be able to include backlink from a namespace (`:aaa:bbb:ccc:`) on a page from another namespace (`:mmm:nnn:ooo:start`).
As @moz0817 i tried several syntaxes but nothing works.

**Comment by mprins** [comment]
What happens when you omit the include, eg.`{{backlinks>.}}`

**Comment by chtiland** [comment]
backlinks from all namespace are displayed

**Comment by mprins** [comment]
OK looks like a bug, may have some time over the weekend, may take longer; so if you want to poke around yourself...

**Comment by mprins** [comment]
I have created a testcase to illustrate your use and it passes, so things just work the way they are supposed to.
