### ISSUE TITLE
Plugin results Server Error 500

### ISSUE THREAD

**Issue by Onkh** [mprins/dokuwiki-plugin-backlinks#7]
Hi @ all,

I installed the tool but it results a breaking of the complete Dokuwiki. Is this case known? 
As soon I installed the plugin, the wiki pages show me Server Error 500.

Best regards
Julian

**Comment by mprins** [comment]
I have not experienced this using this plugin. 
Without any more information (eg. server log) we're unable to help you; please see the issue template: https://github.com/mprins/dokuwiki-plugin-backlinks/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by mprins** [comment]
closing due to lack of response over the last 5 weeks
