### ISSUE TITLE
PHP 7.0 compatibility issue

### ISSUE THREAD

**Issue by sorenweber** [mprins/dokuwiki-plugin-backlinks#8]
## environment
- php version: PHP 7.0.4-7ubuntu2
- dokuwiki version: 2015-08-10a "Detritus"
- plugin version: current stable downloaded via Extension Manager
- list of any other plugins (apart from bundled plugins): 
  acl         authad     authpgsql  backlinks    commentsyntax  data           dw2pdf     gallery    index.html  mathjax   move         odt       pagemod     publish     safefnrecode  syntax.php   templatepagename  userhomepage  wrap
  action.php  authldap   auth.php   bureaucracy  config         discussion     edittable  imageflow  indexmenu   memcache  multiorphan  odt2dw    pagequery   remote.php  sqlite        tag          translation       usermanager
  admin.php   authmysql  authplain  ckgedit      copypage       docnavigation  extension  include    info        message   note         pagelist  popularity  revert      styling       tagsections  upgrade           vshare
## expected behaviour

No error in Apache log
## actual behaviour

Errors in Apache log
## steps to reproduce actaul behaviour

Observe Apache error log when running Ubuntu Server 16.04LTS and accessing dokuwiki (downloaded from dokuwiki.org)
### error log

```
PHP Warning:  Declaration of syntax_plugin_backlinks::handle($match, $state, $pos, &$handler) should be compatible with DokuWiki_Syntax_Plugin::handle($match, $state, $pos, Doku_Handler $handler) in /var/www/html/dokuwiki/lib/plugins/backlinks/syntax.php on line 0, referer: https://dokuwiki/dokuwiki/doku.php/q:start

```
### debug log

```
DEBUG
```

**Comment by mprins** [comment]
this was fixed in february see #5

also: this is a warning, not an error.
